version: '3.8'
services:
  server:
    image: node:latest
    environment:
      TZ: Pacific/Auckland
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 80:80
    entrypoint: npm run nodemon
  vue:
    image: node:latest
    environment:
      TZ: Pacific/Auckland
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: npm run watch