version: '3.8'
services:
  server-dev:
    image: node:16-alpine
    environment:
      TZ: Pacific/Auckland
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 80:80
      - 9229:9229
      - 5858:5858
    entrypoint: npm run nodemon

  server:
    image: node:16-alpine
    environment:
      TZ: Pacific/Auckland
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 80:80
    entrypoint: npm run server

  vue:
    image: node:16-alpine
    environment:
      TZ: Pacific/Auckland
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: npm run watch